### PR TITLE
Remove unsafe access to Socket.Address

### PR DESCRIPTION
**Pull request by mcfedr**
## Description

asAddr funcs were passing unsafe pointers outside of the callbacks in which try should be used
Using callback to make all the access within these callbacks

## Motivation and Context

Fixes bug where IPv6 address was 'cast' to sockaddr but actually was zero'd beyond the length of sockaddr_in and packets written to the wrong address

## Checklist:
- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [N/A] If applicable, I have updated the documentation accordingly.
- [N/A] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by mcfedr** [comment]
I think this might need some review, unfortunately the diff is worse than it needs to be because quite a bit of code just gets indented

**Comment by billabt** [comment]
Yeah, this’ll take awhile. I’ll get to it as soon as I can. At a quick glance, I like it a lot. I’ve always been a bit leery of these functions and was never quite satisfied. Did you submit a CLA? Unfortunately, I can’t take the contribution without one.

**Comment by mcfedr** [comment]
Ok, ill see about the CLA asap. Tomorrow I'll have time to test the changes I've made a bit more thoroughly, I wanted to throw it up here now. I think there are quite a few more manipulations of `sockaddr` that could be changed as well, although the others *look* like that shouldn't cause problems.

With this I was trying to write packet to some IP address `aaaa::bbbb:cccc`, but they were actually written to `aaaa::bbbb:0000`

**Comment by mcfedr** [comment]
Must say, its not very encouraging for the open source nature of the project having to give IBM a license to do what they want with the code.

**Comment by billabt** [comment]
I know what you mean. It’s the lawyers who’ve gummed up the works. I’m getting ready to retire on November 2 and still plan on maintaining this and a few other repos that I’m responsible for and I found out that after I retire, I’ll need to submit a CLA if I want to keep maintaining them. Go figure!!! 🤣

**Comment by billabt** [comment]
@mcfedr Did you decide whether or not to submit a CLA?  I've just about completed the review of this PR and anticipate being able to accept it soon providing I have a CLA.  Thanks.

**Comment by mcfedr** [comment]
Yes. I have sent it in to the contact in the document.

**Comment by billabt** [comment]
@mcfrdr:  Can you send me a copy?  Apparently he hasn’t received it. Please send to my email address, babt@me.com. Thanks.

**Comment by mcfedr** [comment]
Sure, I just forwarded it to you.

**Comment by billabt** [comment]
@mcfedr: I've got just one concern with this PR.  Maybe there's a way around it, maybe it's the best or _only_ way of doing it.  Not sure.  The concern is using the _exception mechanism_ to control flow like you do with **NotAnError**.  It's definitely a _novel_ way of doing it but it almost seems _abusive_ of the exception mechanism, no?  I've been looking at a better way of doing it but so far have come up blank.  Did you also look at alternative ways?

The biggest issue I have with using the _exception mechanism_ for _normal_ flow is **performance**.  It's kinda heavy handed.

On the plus side, the only time that **NotAnError** is thrown is when the _accept is interrupted_ so I guess you could call that an _exception to the normal flow_.

If I (or you) can't come up with a better way by Wednesday, I'm going to go with it and do the merge.  However, I do request that you change the name of **NotAnError** to **OperationInterrupted** or something similar.  Makes it clearer to a reader exactly what is going on and why the exception is being thrown.

Thanks.

**Comment by mcfedr** [comment]
I agree, it felt wrong writing it, but its the only way I could think of to do that early return inside the closures.

Your name is much better, I'll definitely make that change.

**Comment by billabt** [comment]
Ok, cool.  I'm in agreement.  Make the name change and once it passed _CI_, I'll do the merge.  Thanks.

**Comment by billabt** [comment]
@mcfedr:  Something like this maybe?
```
enum OperationInterrupted:  Swift.Error {
    case accept
}
```
Then throw it like this...
```
throw OperationInterrupted.accept
```
Indicating the _accept operation was interrupted_.

**Comment by billabt** [comment]
@mcfedr: If it's ok with you, I'll do the merge and then make the change as I outlined above and then do the release.

**Comment by mcfedr** [comment]
Great. I've been traveling a bit right now so haven't had a chance to get
to it. Glad to see you've handled this.

**Pull request merged**
