### PR TITLE
Implement Travis CI for the repo

### PR DESCRIPTION
**Pull request by BDHernand**
The link to the travis build is here:

https://travis-ci.org/BDHernand/BlueSocket/builds/158757465

Both MacOS and Linux passed

### CODE REVIEW

**Comment by billabt** [comment]
The .swift-version file is `very old`.  BlueSocket is currently up to the 9/11 toolchain...

**Comment by BDHernand** [comment]
@billbt the notifications for the travis are going to be sent to the Kitura slack channel.  Do you want me to remove the notifications section for the travis file?

**Comment by BDHernand** [comment]
@billabt will update the .swift-version file to be 09-07

**Comment by shmuelk** [comment]
@BDHernand The Kitura-Notifications channel is for Kitura stuff. Why do we need noise there from other projects? I believe other project also have there own Notifications channels.....

**Pull request merged**
