### PR TITLE
Standardize README

### PR DESCRIPTION
**Pull request by helenmasters**
* Add community and license sections
 * Add standard README header including Kitura icon

### CODE REVIEW

**Comment by billabt** [comment]
The Blue* frameworks are used by lots of other projects. IMHO, we should not label them with the Kitura icon as it may lead to them being misrepresented as Kitura specific. Thoughts?

**Comment by helenmasters** [comment]
@billabt understood. Would it be an more acceptable if I removed the Kitura icon and left the rest of the header as is? Ideally I'd like to leave the links to Slack and the community section at the end of the README as I don't see why users of the Blue* frameworks couldn't have a small exposure to Kitura, as I don't think these make it look Kitura specific?

**Comment by billabt** [comment]
That sounds fine to me. Thanks. We should probably make the changes to the other Blues ASAP for consistency.

**Comment by helenmasters** [comment]
I'll try and push identical changes to all of the other Blue* repositories by end of day today.

**Comment by billabt** [comment]
Ok, sounds good.  Once that's done, I'll merge them all either tonight or tomorrow morning and do a release.  Thanks.

**Comment by billabt** [comment]
@helenmasters Don't forget **BlueRSA**. 😉 Thanks.

**Pull request merged**
