### PR TITLE
Del xcode xcuserdatad, add set iOS team to none and add xcuserdata/ to gitignore

### PR DESCRIPTION
**Pull request by FlowerWrong**
## Description
Make this project more teamable.

## Motivation and Context
Let us work happy.

## How Has This Been Tested?
Yes.

### CODE REVIEW

**Comment by billabt** [comment]
Did you complete the CLA?  I don't have a record of it being submitted.  Also, in the future, please do not edit the `.swift-version` file.  It's part of our CI build system and expects a specific format...  Thanks for the PR.

**Comment by FlowerWrong** [comment]
@billabt I saw [CLA](https://github.com/IBM-Swift/CLA) just now.

> please do not edit the .swift-version file

ok.

**Comment by billabt** [comment]
This PR was closed due to lack of a signed CLA. If you wish to reopen it, please forward a signed CLA when reopening. Thanks.

**Comment by FlowerWrong** [comment]
ok

**Pull request closed without merging**
