### PR TITLE
Update to changes in upcoming swift 3.0

### PR DESCRIPTION
**Pull request by chrbayer**
Since the hast swift dev version, there are some interface changes so that BlueSocket was not able to be build anymore. This pull request includes necessary changes for BlueSocket to adapt.

### CODE REVIEW

**Comment by kweinmeister** [comment]
Thank you for keeping BlueSocket current with this pull request! Can you please follow the one-time contributor process? https://github.com/IBM-Swift/CLA

**Comment by billabt** [comment]
@chrbayer BlueSocket right now is tracking the released DEVELOPMENT versions of Swift.  We're aware of the changes that are coming and really appreciate your contribution however, until a new release of the toolchain is available, we won't be able to merge your PR.  However, if you'd to like to keep your PR request current with the latest changes, we'd be more than happy to merge it in as soon as a new DEVELOPMENT version of the toolchain is made available.  Thanks again.

**Comment by chrbayer** [comment]
@billabt I fully understand that you have to wait for the released version of swift, I will try to keep the PR update.

**Comment by billabt** [comment]
@chrbayer Thanks.  Much appreciated.

**Comment by billabt** [comment]
@chrbayer Thanks again for your PR. Since the code has been changing so much, I decided to merge the changes in manually. Your PR was invaluable in assisting me in doing so. I'm now going to close this PR but I wanted you to know that it was extremely helpful to me as a reference. Thanks for your contribution and I look forward to any other suggestions you might have on how this library could be improved.

**Pull request closed without merging**
