### PR TITLE
Add Xcode9 and 6-29 snapshot to Travis IBM-Swift/Kitura#1121

### PR DESCRIPTION
**Pull request by quanvo87**
## Checklist:

- [ ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by billabt** [comment]
It looks like it's failing.

**Comment by kweinmeister** [comment]
@billabt Interesting... it looks like the build is failing due to SwiftLint:
```
fatal error: Could not read configuration file at path '/Users/travis/build/IBM-Swift/BlueSocket/.swiftlint.yml': file /tmp/swiftlint-20170618-91032-usukvx/Source/SwiftLintFramework/Models/Configuration.swift, line 161
./Package-Builder/build-package.sh: line 157:  3515 Illegal instruction: 4  (core dumped) swiftlint lint --config ${projectFolder}/.swiftlint.yml
```

**Comment by quanvo87** [comment]
Yes, the tests pass on the 6/29 snapshot on macOS and Linux. I will be looking into the Swift Lint issue.

**Comment by billabt** [comment]
In case you hadn't noticed, BlueSocket overrides the swiftlint settings via a custom .swiftlint.yml and we haven't experienced any problems in the past using it. Is there a new swiftlint being used now?  The problem appears to reading in the file. Maybe there's a stray character in it somewhere that causing it to blow up.

**Comment by quanvo87** [comment]
It could be because I've updated the Xcode version to 8.3, as well as added Xcode 9.

https://github.com/realm/SwiftLint/issues/1452

**Comment by billabt** [comment]
Nope, that's not the problem. I've been running the beta for awhile now without any issues.

**Comment by quanvo87** [comment]
@billabt The build is passing now. We needed another `\` to properly escape the `s` in the regex in `swiftlint.yml`. There must have been a change in SwiftLint or how the .yaml is read in.

Thanks to @youming-lin for help with the issue.

**Pull request merged**
